---
- include: /home/ansible/roles/deploy_docker/tasks/main.yml

- name: Docker login
  shell: docker login -p esu0mtaeB -u beatmouse

    #- name: Log into DockerHub
    #docker_login:
    #registry: hub.docker.com      
    #username: beatmouse
    #password: esu0mtaeB
    #api_version: 1 

- name: Pull app image from DockerHub
  docker_image:
    name: beatmouse/app:latest

- name: Run app container
  docker_container:
    name: "{{ item.name }}"          
    detach: yes
    networks:
    - name: network_one
    ports: "{{ item.ports }}" 
    #tty: yes
    #interactive: yes
    image: beatmouse/app:latest
  with_items:
    - { name: 'app1', ports: '5551:5000' }
    - { name: 'app2', ports: '5552:5000' }
    - { name: 'app3', ports: '5553:5000' }

