---
- include: /home/ansible/roles/deploy_docker/tasks/main.yml

- name: Pull nginx
  docker_image:
    name: nginx

- name: Run app container
  docker_container:
    name: nginx      
    detach: yes
    volume:
    /home/nginx:/etc/nginx
    networks:
    - name: network_one            
    ports: 80:80
    links: app1:app1
    links: app2:app2
    links: app3:app3
    #tty: yes
    #interactive: yes
    image: nginx

    #- name: Generate nginx.conf from template jinja2
    #template src nginx.conf.j2 dest docker /etc/nginx/nginx.conf
