---
- include: /home/ansible/roles/deploy_docker/tasks/main.yml

- name: Pull nginx
  docker_image:
    name: nginx

- name: Run app container
  docker_container:
    name: nginx      
    detach: yes
    networks:
    - name: network_one            
    ports: 80:80
    links: app1:app1
    links: app2:app2
    links: app3:app3
    #tty: yes
    #interactive: yes
    image: nginx

- name: Generate nginx.conf from template jinja2
  template: src=nginx.conf.j2 dest=/home/nginx/nginx.conf

- name: Copy nginx config file   
  command: docker cp /home/nginx/nginx.conf nginx:/etc/nginx/nginx.conf
  
- name: Reload nginx service
  command: docker exec nginx service nginx reload
