--- 
- name: Docker installation
  - name: Update repository
      shell: yum update -y
  - name: Install yum-utils
      yum:
        name: yum-utils
        state: latest
  - name: Install device-mapper
      yum:
        name: device-mapper-persistent-data
        state: latest
  - name: Install lvm2
      yum:
        name: lvm2
        state: latest
  - name: Add repository      
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - name: Install docker-ce
      yum: 
        name: docker-ce  
        state: latest
  shell: systemctl start docker; sudo systemctl enable docker
  service: state=started enabled=yes

- name: Pull app image from DockerHub
  shell: docker pull nginx 
  
- name: Run Nginx
   shell: docker run -d --name nginx -p 80:80 nginx
    
#- name: Generate config file Nginx from Jinja2  
